[module]
integer = "./src/integer.py"
dijkstra = "./src/dijkstra.py"
unionfind = "./src/unionfind.py"

[print_format]
prefix = "printf"
body = ["print('$1'.format($2))"]

[for]
prefix = "for"
body = [
    "for $1 in $2:",
    "\t$3"
    ]

[for_enumerate]
prefix = "fore"
body = [
    "for ${1:i}, $2 in enumerate($3):",
    "\t$3",
    ]

[for_range]
prefix = "forr"
body = [
    "for ${1:i} in range($2):",
    "\t$3",
    ]

[for_items]
prefix = "fori"
body = [
    "for ${1:k}, ${2:v} in $3.items():",
    "\t$4",
    ]